### ISSUE TITLE
Thead fixe et responsive

### ISSUE THREAD

**Issue by Latiatcha** [SNCFdevelopers/bootstrap-sncf#160]
Bonjour,

Nous travaillons avec de très grands tableaux en scroll infinie.
Le soucis rencontré, on ne voit plus le header du tableau. Il y a effectivement la pagination qui pallie à ce problème mais avec des milliers de données cela ne correspond pas aux utilisateurs.
Nous avons souvent besoin de fixer le header et que le tableau reste responsive sous tablette et mobile.

Screenshot des tableaux que nous pouvons avoir :
![screen-bigtableau](https://user-images.githubusercontent.com/26218680/50640123-2ac1c900-0f64-11e9-9c42-f24337e8dfa3.PNG)

Merci,

**Comment by diyfr** [comment]
Tu as essayé cette [solution](https://bootsnipp.com/snippets/oVlgM) ?
```css
.table-fixed thead {
  width: 97%;
}
.table-fixed tbody {
  height: 230px; /* A adapter en fonction de tes besoins*/
  overflow-y: auto;
  width: 100%;
}
.table-fixed thead, .table-fixed tbody, .table-fixed tr, .table-fixed td, .table-fixed th {
  display: block;
}
.table-fixed tbody td, .table-fixed thead > tr> th {
  float: left;
  border-bottom-width: 0;
}
```

```html
 <table class="table table-fixed">
```
