### ISSUE TITLE
Erreur dans le package NPM

### ISSUE THREAD

**Issue by diyfr** [SNCFdevelopers/bootstrap-sncf#192]
Dans le package node @sncf/bootstrap-sncf.metier
Il y a une erreur de formatage dans le css au niveau de la déclaration du `content`
Nous avons
```css
.breadcrumb-item+.breadcrumb-item::before{
display:inline-block;
padding-right:1rem;
padding-left:1rem;
color:#333;
content:"url(\"data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 50 50'%3E%3Cpath fill='%23b9b9b9' d='M40.42 25 17 48.85a4.69 4.69 0 0 1-6.15 0,5.15 5.15 0 0 1-1.16-3.08 4.38 4.38 0 0 1 1.16-3.08L28.12 25 10.81 7.31A4.6 4.6 0 0 1 11.58.38a5.39 5.39 0 0 1 5.77 1.16Z'/%3E%3C/svg%3E\")"
}
````
on devrait avoir un truc dans le genre
```css
.breadcrumb-item+.breadcrumb-item::before{
display:inline-block;
padding-right:1rem;
padding-left:1rem;
color:#333;
content:url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 50 50'%3E%3Cpath fill='%23b9b9b9' d='M40.42 25 17 48.85a4.69 4.69 0 0 1-6.15 0,5.15 5.15 0 0 1-1.16-3.08 4.38 4.38 0 0 1 1.16-3.08L28.12 25 10.81 7.31A4.6 4.6 0 0 1 11.58.38a5.39 5.39 0 0 1 5.77 1.16Z'/%3E%3C/svg%3E")
}
````
En ouput on ne peut pas avoir d'échappement sur les doubles quotes sur un CSS

Je situerais le problème par là
https://github.com/SNCFdevelopers/bootstrap-sncf/blob/master/src/scss/common/components/_breadcrumb.scss#L17

Serait-il possible aussi d'ajouter la version non-minifiée dans le package
