### ISSUE TITLE
Présence de variables SCSS dans le fichier CSS bootstrap-sncf.css

### ISSUE THREAD

**Issue by HarmonicTons** [SNCFdevelopers/bootstrap-sncf#210]
Hello,

Le fichier final "@sncf/bootstrap-sncf.metier/dist/bootstrap-sncf.css" contient encore quelques variables SCSS: `$mastheader-height`, `$actionbar-min-height`, `$actionbar-max-height` et `$controlbar-height` dans le selector media ligne 10827:

```css
@media (max-width: 767.98px) {
  .mastheader + .mastcontainer .table-vh {
    height: calc(100vh - $mastheader-height); }
  .mastheader + .actionbar + .mastcontainer .table-vh {
    height: calc(100vh - ($mastheader-height + $actionbar-min-height)); }
  .mastheader + .actionbar.has-tabs + .mastcontainer .table-vh {
    height: calc(100vh - ($mastheader-height + $actionbar-max-height)); }
  .mastheader + .actionbar + .controlbar + .mastcontainer .table-vh {
    height: calc(100vh - ($mastheader-height + $actionbar-min-height + $controlbar-height)); }
  .mastheader + .actionbar.has-tabs + .controlbar + .mastcontainer .table-vh {
    height: calc(100vh - ($mastheader-height + $actionbar-max-height + $controlbar-height)); } }
```

La présence de ces variables empêche d'utiliser le bootstrap métier dans un build sans préprocesseur SCSS, et produit ce genre d'error stack:

```
=============
Failed to compile.

Lexical error on line 1: Unrecognized text.
  Erroneous area:
1: 100vh - $mastheader-height
^..........^
```

**Comment by HarmonicTons** [comment]
Un fix (très temporaire) consiste à mettre à jour à la main le fichier bootstrap-sncf.css avec les valeurs correspondants aux variables:

```css
@media (max-width: 767.98px) {
  .mastheader + .mastcontainer .table-vh {
    height: calc(100vh - 3.75rem); }
  .mastheader + .actionbar + .mastcontainer .table-vh {
    height: calc(100vh - (3.75rem + 3.875rem)); }
  .mastheader + .actionbar.has-tabs + .mastcontainer .table-vh {
    height: calc(100vh - (3.75rem + 5.625rem)); }
  .mastheader + .actionbar + .controlbar + .mastcontainer .table-vh {
    height: calc(100vh - (3.75rem + 3.875rem + 2.5rem)); }
  .mastheader + .actionbar.has-tabs + .controlbar + .mastcontainer .table-vh {
    height: calc(100vh - (3.75rem + 5.625rem + 2.5rem)); } }
```
